/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('ant-design-vue/es')['App']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AdminLayout: typeof import('./src/components/layouts/admin/AdminLayout.vue')['default']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AppProvider: typeof import('./src/components/providers/AppProvider.vue')['default']
    ASpace: typeof import('ant-design-vue/es')['Space']
    BaseLayout: typeof import('./src/components/layouts/public/BaseLayout.vue')['default']
    ConfigProvider: typeof import('./src/components/providers/ConfigProvider.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PublicContent: typeof import('./src/components/layouts/public/PublicContent.vue')['default']
    PublicFooter: typeof import('./src/components/layouts/public/PublicFooter.vue')['default']
    PublicHeader: typeof import('./src/components/layouts/public/PublicHeader.vue')['default']
    PublicLayout: typeof import('./src/components/layouts/public/PublicLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
